/**
 * SANOCEA SEO Stack — Phase 2 Crawler Independence Test Suite
 * 
 * Verifies that the crawler can autonomously audit client-rendered Single-Page Applications (SPA)
 * using built-in Playwright/Chromium with zero external callbacks or manual configuration.
 */

import { test } from 'node:test';
import assert from 'node:assert/strict';
import * as http from 'node:http';
import { BrowserPool } from '../src/core/browserPool.js';
import { DualEngineCrawler, evaluateJsEscalationNeed } from '../src/core/crawler.js';

test('Phase 2.1 — BrowserPool: Autonomous Chromium Rendering & DOM Hydration', async () => {
  const browserPool = BrowserPool.getInstance();

  // Test client-rendered SPA fixture with inline script DOM mutation
  const spaHtml = `
    <!DOCTYPE html>
    <html lang="en">
      <head>
        <meta charset="utf-8">
        <title>Loading SPA Shell...</title>
      </head>
      <body>
        <div id="root"></div>
        <script>
          // Simulate React / Vue client-side mounting
          const root = document.getElementById('root');
          root.innerHTML = \`
            <h1>Autonomous Playwright Escalation Proven</h1>
            <p>This content was dynamically generated by client-side JavaScript execution.</p>
            <nav>
              <a href="/products/solar-inverter">Inverter 5kW</a>
              <a href="/solutions/commercial">Commercial Solutions</a>
            </nav>
          \`;
          document.title = 'Hydrated Single-Page App | SANOCEA Verified';
        </script>
      </body>
    </html>
  `;

  const result = await browserPool.renderContent(spaHtml);

  assert.ok(result.renderedHtml.includes('Autonomous Playwright Escalation Proven'), 'Must execute JS and render H1');
  assert.ok(result.renderedHtml.includes('Inverter 5kW'), 'Must render client navigation links');
  assert.ok(result.renderedHtml.includes('Hydrated Single-Page App'), 'Must reflect client-mutated page title');
  assert.ok(result.executionTimeMs >= 0);
});

test('Phase 2.2 — DualEngineCrawler: Autonomous Escalation on Live HTTP SPA Server', async () => {
  // Spin up an ephemeral local HTTP server serving a React SPA shell
  const server = http.createServer((req, res) => {
    if (req.url === '/' || req.url === '/index.html') {
      res.writeHead(200, { 'Content-Type': 'text/html' });
      res.end(`
        <!DOCTYPE html>
        <html>
          <head>
            <meta charset="utf-8">
            <title>SPA Root Shell</title>
            <script type="module" src="/main.js"></script>
          </head>
          <body>
            <div id="root"></div>
            <script>
              document.getElementById('root').innerHTML = \`
                <h1>Autonomous Headless Crawler Success</h1>
                <nav>
                  <a href="/subpage-alpha">Subpage Alpha</a>
                  <a href="/subpage-beta">Subpage Beta</a>
                </nav>
              \`;
            </script>
          </body>
        </html>
      `);
    } else {
      res.writeHead(200, { 'Content-Type': 'text/html' });
      res.end(`<html><body><h1>${req.url}</h1><a href="/">Home</a></body></html>`);
    }
  });

  await new Promise<void>((resolve) => server.listen(0, '127.0.0.1', () => resolve()));
  const address = server.address() as any;
  const baseUrl = `http://127.0.0.1:${address.port}/`;

  try {
    // 1. Verify JS escalation need heuristic flags the SPA shell
    const rawResp = await fetch(baseUrl);
    const rawHtml = await rawResp.text();
    const escalation = evaluateJsEscalationNeed(rawHtml);
    assert.ok(escalation.needsEscalation, 'Must detect empty root mount container and missing SSR H1');

    // 2. Initialize DualEngineCrawler WITHOUT any custom renderer callback
    const crawler = new DualEngineCrawler({
      seedUrl: baseUrl,
      maxPages: 3,
      maxDepth: 1,
      allowSubdomains: false,
      enableJsRendering: true // Built-in Playwright will autonomously engage
    });

    const page = await crawler.crawlSingle(baseUrl);

    // 3. Verify that the page was autonomously escalated and rendered by built-in Playwright
    assert.equal(page.isJsRendered, true, 'Page must be autonomously marked isJsRendered = true');
    assert.ok(page.renderedHtml, 'renderedHtml must be populated');
    assert.ok(page.renderedHtml.includes('Autonomous Headless Crawler Success'), 'Rendered HTML must contain client-rendered H1');

    // 4. Verify that dynamically rendered internal links were discovered
    const subpageAlphaLink = page.discoveredUrls.find(u => u.url.includes('/subpage-alpha'));
    const subpageBetaLink = page.discoveredUrls.find(u => u.url.includes('/subpage-beta'));
    assert.ok(subpageAlphaLink, 'Must discover client-rendered /subpage-alpha outlink');
    assert.ok(subpageBetaLink, 'Must discover client-rendered /subpage-beta outlink');

    await crawler.close();
  } finally {
    await new Promise<void>((resolve) => server.close(() => resolve()));
    await BrowserPool.getInstance().close();
  }
});
